# This file contains named vector fo all short names used in the GUI analysis.

var.labels = c(cq3g2a = "high_inc",
               cq3g2b = "training_opp",
               cq3g2c = "interesting_job",
               cq3g2d = "flex_hours",
               cq3g2e = "time_off",
               cq3g2f = "good_for_career",
               cq3g2g = "being_boss",
               cq3g2h = "help_society",
               cq3g2i = "job_security",
               cq3g2j = "travel_abroad",
               cq3g2k = "other",
               p2sexW3 = "gender",
               pc3f1educ = "PC1_edu",
               p1empW3 = "PC1_emp",
               w3equivinc = "equalised_inc",
               cq3g4f = "work_imp",
               cq3g4h ="religion_imp",
               cq3g4j ="own_family_imp",
               Cog_scores = "cognitive_scores",
               cq3b4a = "TY",
               w3cq_conscientious = "conscientious_score",
               ID = "ID",
               cq3a3ayr = "left_school",
               imp_school_type = "school_type",
               schoolID = "schoolID",
               hopa = "parental_interactions",
               guidance ="career_guidance",
               cq3f1 = "part_time_job",
               cq3f5 = "work_for_business",
               cq3f6 = "work_exp",
               adsd60 = "household_region"
               
               )