# This file contains named vector fo all short names used in the GUI analysis.

var.labels = c(cq4J5a = "high_inc",
               cq4J5b = "training_opp",
               cq4J5c = "promotion_opp",
               cq4J5d = "interesting_job",
               cq4J5f = "time_off",
               cq4J5g = "good_for_career",
               cq4J5h = "being_boss",
               cq4J5j = "help_society",
               cq4J5k = "job_security",
               cq4J5l = "travel_abroad",
               cq4J5e = "flex_hours",
               cq4J5i = "creative_job",
               p2sexW3 = "gender",
               pc3f1educ = "PC1_edu",
               p1empW3 = "PC1_emp",
               w3equivinc = "equalised_inc",
               cq3g4f = "work_imp",
               cq3g4h ="religion_imp",
               cq3g4j ="own_family_imp",
               Cog_scores = "cognitive_scores",
               cq3b4a = "TY",
               w3cq_conscientious = "conscientious_score",
               ID = "ID",
               cq3a3ayr = "left_school",
               imp_school_type = "school_type",
               schoolID = "schoolID",
               hopa = "parental_interactions",
               guidance ="career_guidance",
               cq3f1 = "part_time_job",
               cq3f5 = "work_for_business",
               cq3f6 = "work_exp",
               adsd60 = "household_region")